# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forestry_Photo_Viewer_value.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForestryPhotoViewerDialogBase(object):
    def setupUi(self, ForestryPhotoViewerDialogBase):
        ForestryPhotoViewerDialogBase.setObjectName("ForestryPhotoViewerDialogBase")
        ForestryPhotoViewerDialogBase.resize(370, 150)
        ForestryPhotoViewerDialogBase.setMinimumSize(QtCore.QSize(370, 150))
        ForestryPhotoViewerDialogBase.setMaximumSize(QtCore.QSize(370, 150))
        self.Subject = QtWidgets.QLineEdit(ForestryPhotoViewerDialogBase)
        self.Subject.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.Subject.setObjectName("Subject")
        self.Forestry = QtWidgets.QLineEdit(ForestryPhotoViewerDialogBase)
        self.Forestry.setGeometry(QtCore.QRect(10, 60, 171, 20))
        self.Forestry.setObjectName("Forestry")
        self.PrForestry = QtWidgets.QLineEdit(ForestryPhotoViewerDialogBase)
        self.PrForestry.setGeometry(QtCore.QRect(10, 90, 171, 20))
        self.PrForestry.setObjectName("PrForestry")
        self.label_1 = QtWidgets.QLabel(ForestryPhotoViewerDialogBase)
        self.label_1.setGeometry(QtCore.QRect(190, 30, 101, 16))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(ForestryPhotoViewerDialogBase)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ForestryPhotoViewerDialogBase)
        self.label_3.setGeometry(QtCore.QRect(190, 90, 91, 16))
        self.label_3.setObjectName("label_3")
        self.OKButton = QtWidgets.QPushButton(ForestryPhotoViewerDialogBase)
        self.OKButton.setGeometry(QtCore.QRect(290, 120, 75, 23))
        self.OKButton.setObjectName("OKButton")
        self.label_4 = QtWidgets.QLabel(ForestryPhotoViewerDialogBase)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 261, 16))
        self.label_4.setObjectName("label_4")
        self.remember_1 = QtWidgets.QCheckBox(ForestryPhotoViewerDialogBase)
        self.remember_1.setGeometry(QtCore.QRect(290, 30, 81, 17))
        self.remember_1.setObjectName("remember_1")
        self.remember_2 = QtWidgets.QCheckBox(ForestryPhotoViewerDialogBase)
        self.remember_2.setGeometry(QtCore.QRect(290, 60, 81, 17))
        self.remember_2.setObjectName("remember_2")
        self.remember_3 = QtWidgets.QCheckBox(ForestryPhotoViewerDialogBase)
        self.remember_3.setGeometry(QtCore.QRect(290, 90, 81, 17))
        self.remember_3.setObjectName("remember_3")

        self.retranslateUi(ForestryPhotoViewerDialogBase)
        QtCore.QMetaObject.connectSlotsByName(ForestryPhotoViewerDialogBase)

    def retranslateUi(self, ForestryPhotoViewerDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ForestryPhotoViewerDialogBase.setWindowTitle(_translate("ForestryPhotoViewerDialogBase", "Значение полей"))
        self.label_1.setText(_translate("ForestryPhotoViewerDialogBase", "Субъект (область)"))
        self.label_2.setText(_translate("ForestryPhotoViewerDialogBase", "Лесничество"))
        self.label_3.setText(_translate("ForestryPhotoViewerDialogBase", "Уч. Лесничество"))
        self.OKButton.setText(_translate("ForestryPhotoViewerDialogBase", "OK"))
        self.label_4.setText(
            _translate("ForestryPhotoViewerDialogBase", "Укажите данные для внесения в файл привязки."))
        self.remember_1.setText(_translate("ForestryPhotoViewerDialogBase", "Запомнить"))
        self.remember_2.setText(_translate("ForestryPhotoViewerDialogBase", "Запомнить"))
        self.remember_3.setText(_translate("ForestryPhotoViewerDialogBase", "Запомнить"))
