# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forestry_Photo_Viewer_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from .resources import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForestryPhotoViewerDialogBase(object):
    def setupUi(self, ForestryPhotoViewerDialogBase):
        ForestryPhotoViewerDialogBase.setObjectName("ForestryPhotoViewerDialogBase")
        ForestryPhotoViewerDialogBase.resize(487, 222)
        ForestryPhotoViewerDialogBase.setMinimumSize(QtCore.QSize(487, 222))
        ForestryPhotoViewerDialogBase.setMaximumSize(QtCore.QSize(487, 222))
        self.tabWidget = QtWidgets.QTabWidget(ForestryPhotoViewerDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 471, 171))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.files = QtWidgets.QLabel(self.tab)
        self.files.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.files.setObjectName("files")
        self.button = QtWidgets.QPushButton(self.tab)
        self.button.setGeometry(QtCore.QRect(220, 10, 91, 23))
        self.button.setObjectName("button")
        self.layerBox_1 = QtWidgets.QComboBox(self.tab)
        self.layerBox_1.setGeometry(QtCore.QRect(10, 40, 221, 22))
        self.layerBox_1.setObjectName("layerBox_1")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(240, 40, 171, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 351, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 201, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 261, 21))
        self.label_4.setObjectName("label_4")
        self.sort_1 = QtWidgets.QPushButton(self.tab)
        self.sort_1.setGeometry(QtCore.QRect(320, 10, 131, 23))
        self.sort_1.setObjectName("sort_1")
        self.import_1 = QtWidgets.QPushButton(self.tab)
        self.import_1.setGeometry(QtCore.QRect(380, 40, 34, 29))
        self.import_1.setStyleSheet("background-image: url(:/plugins/forestry_Photo_Viewer/import.png);")
        self.import_1.setText("")
        self.import_1.setObjectName("import_1")
        self.export_1 = QtWidgets.QPushButton(self.tab)
        self.export_1.setGeometry(QtCore.QRect(420, 40, 35, 29))
        self.export_1.setStyleSheet("background-image: url(:/plugins/forestry_Photo_Viewer/export.png);")
        self.export_1.setText("")
        self.export_1.setObjectName("export_1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layerBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.layerBox_2.setGeometry(QtCore.QRect(10, 70, 221, 22))
        self.layerBox_2.setObjectName("layerBox_2")
        self.files_2 = QtWidgets.QLabel(self.tab_2)
        self.files_2.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.files_2.setObjectName("files_2")
        self.directory = QtWidgets.QToolButton(self.tab_2)
        self.directory.setGeometry(QtCore.QRect(420, 110, 31, 20))
        self.directory.setObjectName("directory")
        self.layerlabel = QtWidgets.QLabel(self.tab_2)
        self.layerlabel.setGeometry(QtCore.QRect(240, 70, 171, 20))
        self.layerlabel.setObjectName("layerlabel")
        self.path = QtWidgets.QLineEdit(self.tab_2)
        self.path.setGeometry(QtCore.QRect(10, 110, 401, 20))
        self.path.setObjectName("path")
        self.button_2 = QtWidgets.QPushButton(self.tab_2)
        self.button_2.setGeometry(QtCore.QRect(330, 10, 121, 23))
        self.button_2.setObjectName("button_2")
        self.substitution = QtWidgets.QCheckBox(self.tab_2)
        self.substitution.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.substitution.setObjectName("substitution")
        self.binding = QtWidgets.QCheckBox(self.tab_2)
        self.binding.setGeometry(QtCore.QRect(150, 40, 161, 17))
        self.binding.setObjectName("binding")
        self.fields_setting = QtWidgets.QPushButton(self.tab_2)
        self.fields_setting.setGeometry(QtCore.QRect(350, 40, 101, 23))
        self.fields_setting.setObjectName("fields_setting")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layerBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.layerBox_3.setGeometry(QtCore.QRect(10, 40, 221, 22))
        self.layerBox_3.setObjectName("layerBox_3")
        self.layerlabel_2 = QtWidgets.QLabel(self.tab_3)
        self.layerlabel_2.setGeometry(QtCore.QRect(240, 40, 171, 20))
        self.layerlabel_2.setObjectName("layerlabel_2")
        self.files_3 = QtWidgets.QLabel(self.tab_3)
        self.files_3.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.files_3.setObjectName("files_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 341, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 391, 20))
        self.label_6.setObjectName("label_6")
        self.sort_2 = QtWidgets.QPushButton(self.tab_3)
        self.sort_2.setGeometry(QtCore.QRect(320, 10, 131, 23))
        self.sort_2.setObjectName("sort_2")
        self.button_3 = QtWidgets.QPushButton(self.tab_3)
        self.button_3.setGeometry(QtCore.QRect(220, 10, 91, 23))
        self.button_3.setObjectName("button_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.Cancel = QtWidgets.QPushButton(ForestryPhotoViewerDialogBase)
        self.Cancel.setGeometry(QtCore.QRect(400, 190, 75, 23))
        self.Cancel.setObjectName("Cancel")
        self.OK = QtWidgets.QPushButton(ForestryPhotoViewerDialogBase)
        self.OK.setGeometry(QtCore.QRect(310, 190, 75, 23))
        self.OK.setObjectName("OK")
        self.progressBar = QtWidgets.QProgressBar(ForestryPhotoViewerDialogBase)
        self.progressBar.setGeometry(QtCore.QRect(10, 190, 191, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(ForestryPhotoViewerDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ForestryPhotoViewerDialogBase)

    def retranslateUi(self, ForestryPhotoViewerDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ForestryPhotoViewerDialogBase.setWindowTitle(
            _translate("ForestryPhotoViewerDialogBase", "Forestry Photo Viewer"))
        self.files.setText(_translate("ForestryPhotoViewerDialogBase", "Выбрано файлов: 0"))
        self.button.setToolTip(
            _translate("ForestryPhotoViewerDialogBase", "<html><head/><body><p>Выбор снимков</p></body></html>"))
        self.button.setText(_translate("ForestryPhotoViewerDialogBase", "Выбрать файлы"))
        self.label.setText(_translate("ForestryPhotoViewerDialogBase", "Слой полигоны - выдела"))
        self.label_2.setText(
            _translate("ForestryPhotoViewerDialogBase", "Выбирите снимки фотофиксации ПАРМ для привязки к слою."))
        self.label_3.setText(_translate("ForestryPhotoViewerDialogBase", "Для просмотра привязаных снимков: "))
        self.label_4.setText(
            _translate("ForestryPhotoViewerDialogBase", "Выделите нужные выдела и нажмите \'P\' (Photo)"))
        self.sort_1.setToolTip(_translate("ForestryPhotoViewerDialogBase",
                                          "<html><head/><body><p>Отсортировать выбранные файлы по уч. лесничествам</p></body></html>"))
        self.sort_1.setText(_translate("ForestryPhotoViewerDialogBase", "Отсортировать файлы"))
        self.import_1.setToolTip(_translate("ForestryPhotoViewerDialogBase",
                                            "<html><head/><body><p>Импорт файла привязки</p></body></html>"))
        self.export_1.setToolTip(_translate("ForestryPhotoViewerDialogBase",
                                            "<html><head/><body><p>Экспорт файла привязки</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab),
                                  _translate("ForestryPhotoViewerDialogBase", "Привязка снимков к слою"))
        self.files_2.setText(_translate("ForestryPhotoViewerDialogBase", "Выбрано файлов: 0"))
        self.directory.setToolTip(_translate("ForestryPhotoViewerDialogBase",
                                             "<html><head/><body><p>Каталог для сохранения выходных файлов</p></body></html>"))
        self.directory.setText(_translate("ForestryPhotoViewerDialogBase", "..."))
        self.layerlabel.setText(_translate("ForestryPhotoViewerDialogBase", "Слой полигоны - выдела"))
        self.button_2.setToolTip(
            _translate("ForestryPhotoViewerDialogBase", "<html><head/><body><p>Выбор снимков</p></body></html>"))
        self.button_2.setText(_translate("ForestryPhotoViewerDialogBase", "Выбрать файлы"))
        self.substitution.setToolTip(_translate("ForestryPhotoViewerDialogBase",
                                                "<html><head/><body><p>Замена времени в файлах привязки на созданное искусственно</p></body></html>"))
        self.substitution.setText(_translate("ForestryPhotoViewerDialogBase", "Замена времени"))
        self.binding.setToolTip(_translate("ForestryPhotoViewerDialogBase",
                                           "<html><head/><body><p>Создание файла привязки для сделанных снимков</p></body></html>"))
        self.binding.setText(_translate("ForestryPhotoViewerDialogBase", "Создание файла привязки"))
        self.fields_setting.setToolTip(_translate("ForestryPhotoViewerDialogBase",
                                                  "<html><head/><body><p>Настройка текстовых данных для внесения в файл привязки</p></body></html>"))
        self.fields_setting.setText(_translate("ForestryPhotoViewerDialogBase", "Настройка полей"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  _translate("ForestryPhotoViewerDialogBase", "Преобразование файлов"))
        self.layerlabel_2.setText(_translate("ForestryPhotoViewerDialogBase", "Слой полигоны - выдела"))
        self.files_3.setText(_translate("ForestryPhotoViewerDialogBase", "Выбрано файлов: 0"))
        self.label_5.setText(
            _translate("ForestryPhotoViewerDialogBase", "Создаёт ведомость фотофиксации на рабочем слоле."))
        self.label_6.setText(
            _translate("ForestryPhotoViewerDialogBase", " В ней перечисленны выдела с кратким таксационным описанием"))
        self.sort_2.setToolTip(_translate("ForestryPhotoViewerDialogBase",
                                          "<html><head/><body><p>Отсортировать выбранные файлы по уч. лесничествам</p></body></html>"))
        self.sort_2.setText(_translate("ForestryPhotoViewerDialogBase", "Отсортировать файлы"))
        self.button_3.setToolTip(
            _translate("ForestryPhotoViewerDialogBase", "<html><head/><body><p>Выбор снимков</p></body></html>"))
        self.button_3.setText(_translate("ForestryPhotoViewerDialogBase", "Выбрать файлы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3),
                                  _translate("ForestryPhotoViewerDialogBase", "Ведомость фотофиксации"))
        self.Cancel.setText(_translate("ForestryPhotoViewerDialogBase", "Отмена"))
        self.OK.setText(_translate("ForestryPhotoViewerDialogBase", "OK"))
