# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ForestryPhotoViewerDialog
                                 A QGIS plugin
 View photo fixation of the selection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-30
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Travin Alexzander/Roslesinforg
        email                : Alexzander721@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets
from qgis.PyQt import uic

from .Forestry_Photo_Viewer_Main import Ui_ForestryPhotoViewerDialogBase as Ui_Widget_1
from .Forestry_Photo_Viewer_Auxiliary import Ui_ForestryPhotoViewerDialogBase as Ui_Widget_2


class MainWindow(QtWidgets.QDialog, Ui_Widget_1):
    def __init__(self, parent=None):
        """Constructor."""
        super(MainWindow, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)


class AuxiliaryWindow(QtWidgets.QDialog, Ui_Widget_2):
    def __init__(self, parent=None):
        """Constructor."""
        super(AuxiliaryWindow, self).__init__(parent)
        self.setupUi(self)
